// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxGQZ_gQPRP4cH3y2Rb0ZAOMSXKAJm5_M',
    appId: '1:307128675989:web:4a7ffc332d075a6a0df59c',
    messagingSenderId: '307128675989',
    projectId: 'exam-cart-app',
    authDomain: 'exam-cart-app.firebaseapp.com',
    storageBucket: 'exam-cart-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrKIQv8O6yVLQst-Xlz9iPsr4inHZsEaU',
    appId: '1:307128675989:android:3c4bc2d5f5375ce70df59c',
    messagingSenderId: '307128675989',
    projectId: 'exam-cart-app',
    storageBucket: 'exam-cart-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt16k73C9myZe-FOauk_YidqafwNTSeeM',
    appId: '1:307128675989:ios:165b89b63e5610b20df59c',
    messagingSenderId: '307128675989',
    projectId: 'exam-cart-app',
    storageBucket: 'exam-cart-app.appspot.com',
    iosClientId: '307128675989-j4kt24k3e20ddql8vcv82m2pagffpf0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.examApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt16k73C9myZe-FOauk_YidqafwNTSeeM',
    appId: '1:307128675989:ios:e48eb0b7e2f4eef50df59c',
    messagingSenderId: '307128675989',
    projectId: 'exam-cart-app',
    storageBucket: 'exam-cart-app.appspot.com',
    iosClientId: '307128675989-aa0i4tjuaeoec5brqh14o2ec3l7tocjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.examApp.RunnerTests',
  );
}
